
package report

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/kitfind/kitfind/internal/scanner"
)


type Format string

const (
	FormatJSON Format = "json"
	FormatCSV  Format = "csv"
	FormatHTML Format = "html"
	FormatText Format = "txt"
)


func Generate(res *scanner.Result, format Format, outDir string) (string, error) {
	if err := os.MkdirAll(outDir, 0750); err != nil {
		return "", err
	}

	ts := time.Now().Format("20060102-150405")
	domain := strings.ReplaceAll(res.Domain, ".", "_")
	filename := fmt.Sprintf("kitfind_%s_%s.%s", domain, ts, string(format))
	path := filepath.Join(outDir, filename)

	switch format {
	case FormatJSON:
		return path, writeJSON(res, path)
	case FormatCSV:
		return path, writeCSV(res, path)
	case FormatHTML:
		return path, writeHTML(res, path)
	case FormatText:
		return path, writeText(res, path)
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}


func writeJSON(res *scanner.Result, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(res)
}


func writeCSV(res *scanner.Result, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	w := csv.NewWriter(f)
	defer w.Flush()


	_ = w.Write([]string{"target", "severity", "category", "title", "description", "remediation"})

	for _, finding := range res.Findings {
		_ = w.Write([]string{
			res.Target,
			finding.Severity,
			finding.Category,
			finding.Title,
			finding.Description,
			finding.Remediation,
		})
	}
	return w.Error()
}


func writeText(res *scanner.Result, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	line := func(format string, a ...any) {
		fmt.Fprintf(f, format+"\n", a...)
	}

	line("═══════════════════════════════════════════════════════════")
	line("  KITFIND SECURITY REPORT")
	line("═══════════════════════════════════════════════════════════")
	line("  Target  : %s", res.Target)
	line("  Domain  : %s", res.Domain)
	line("  Scanned : %s", res.StartedAt.Format("2006-01-02 15:04:05"))
	line("  Duration: %s", res.Duration)
	line("  Risk    : %d/100 (Grade %s)", res.RiskScore, res.RiskGrade)
	line("")

	if res.DNS != nil {
		line("───────────────────────────────────────────────────────────")
		line("  DNS RECORDS")
		line("───────────────────────────────────────────────────────────")
		for _, r := range res.DNS.Records {
			line("  %-8s  %-40s  TTL=%d", r.Type, r.Value, r.TTL)
		}
		if res.DNS.SPF != "" {
			line("  SPF     : %s", res.DNS.SPF)
		}
		if res.DNS.DMARC != "" {
			line("  DMARC   : %s", res.DNS.DMARC)
		}
		line("")
	}

	if res.SSL != nil {
		line("───────────────────────────────────────────────────────────")
		line("  SSL/TLS")
		line("───────────────────────────────────────────────────────────")
		line("  Version     : %s", res.SSL.TLSVersion)
		line("  Cipher      : %s", res.SSL.CipherSuite)
		line("  Grade       : %s", res.SSL.Grade)
		if res.SSL.Certificate != nil {
			c := res.SSL.Certificate
			line("  Common Name : %s", c.Subject.CommonName)
			line("  Issuer      : %s", c.Issuer.CommonName)
			line("  Expires     : %s (%d days)", c.NotAfter.Format("2006-01-02"), c.DaysUntilExpiry)
			if c.IsWildcard {
				line("  Wildcard    : yes")
			}
		}
		line("")
	}

	if res.HTTP != nil {
		line("───────────────────────────────────────────────────────────")
		line("  HTTP SECURITY HEADERS")
		line("───────────────────────────────────────────────────────────")
		for _, check := range res.HTTP.Checks {
			status := "MISSING"
			if check.Present {
				status = "OK"
			}
			line("  %-8s  %s", status, check.Name)
		}
		line("")
	}

	if res.Fingerprint != nil {
		line("───────────────────────────────────────────────────────────")
		line("  TECHNOLOGY STACK")
		line("───────────────────────────────────────────────────────────")
		for _, t := range res.Fingerprint.Technologies {
			line("  %-20s  %s  (confidence: %d%%)", t.Name, t.Category, t.Confidence)
		}
		line("")
	}

	if len(res.Findings) > 0 {
		line("───────────────────────────────────────────────────────────")
		line("  FINDINGS")
		line("───────────────────────────────────────────────────────────")
		for i, f := range res.Findings {
			line("  [%d] %-8s  %s", i+1, strings.ToUpper(f.Severity), f.Title)
			line("       Category    : %s", f.Category)
			line("       Description : %s", f.Description)
			if f.Remediation != "" {
				line("       Remediation : %s", f.Remediation)
			}
			line("")
		}
	}

	line("═══════════════════════════════════════════════════════════")
	line("  Generated by KitFind v1.0.0  |  %s", time.Now().Format("2006-01-02 15:04:05"))
	line("═══════════════════════════════════════════════════════════")
	return nil
}


func writeHTML(res *scanner.Result, path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	tmpl, err := template.New("report").Funcs(template.FuncMap{
		"upper": strings.ToUpper,
		"inc": func(i int) int { return i + 1 },
		"sevClass": func(sev string) string {
			switch sev {
			case "critical":
				return "sev-critical"
			case "high":
				return "sev-high"
			case "medium":
				return "sev-medium"
			case "low":
				return "sev-low"
			default:
				return "sev-info"
			}
		},
		"gradeClass": func(grade string) string {
			switch grade {
			case "A", "A+":
				return "grade-a"
			case "B":
				return "grade-b"
			case "C":
				return "grade-c"
			default:
				return "grade-f"
			}
		},
	}).Parse(htmlTemplate)
	if err != nil {
		return err
	}

	data := struct {
		Result    *scanner.Result
		Generated string
	}{
		Result:    res,
		Generated: time.Now().Format("2006-01-02 15:04:05 UTC"),
	}

	return tmpl.Execute(f, data)
}

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KitFind Report — {{.Result.Target}}</title>
<style>
  :root {
    --bg: #0d0d0d; --surface: #161616; --border: #2a2a2a;
    --cyan: #00d4ff; --green: #00ff88; --yellow: #ffd700;
    --red: #ff4444; --orange: #ff8800; --text: #e0e0e0;
    --dim: #666; --font: 'Courier New', monospace;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: var(--font); font-size: 14px; padding: 2rem; }
  h1 { color: var(--cyan); font-size: 2rem; letter-spacing: 4px; margin-bottom: 0.25rem; }
  h2 { color: var(--cyan); font-size: 1rem; letter-spacing: 2px; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; margin: 2rem 0 1rem; text-transform: uppercase; }
  .header { border: 1px solid var(--cyan); padding: 1.5rem; margin-bottom: 2rem; }
  .meta { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-top: 1rem; }
  .meta-item label { color: var(--dim); font-size: 0.75rem; display: block; }
  .meta-item span { color: var(--text); font-size: 0.95rem; }
  .risk-score { font-size: 2.5rem; font-weight: bold; }
  .grade-a { color: var(--green); }
  .grade-b { color: #88ff00; }
  .grade-c { color: var(--yellow); }
  .grade-f { color: var(--red); }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
  th { background: #1a1a2e; color: var(--cyan); text-align: left; padding: 0.5rem 0.75rem; font-size: 0.8rem; letter-spacing: 1px; border: 1px solid var(--border); }
  td { padding: 0.5rem 0.75rem; border: 1px solid var(--border); font-size: 0.85rem; }
  tr:nth-child(even) td { background: #111; }
  .sev-critical { color: var(--red); font-weight: bold; }
  .sev-high { color: var(--orange); }
  .sev-medium { color: var(--yellow); }
  .sev-low { color: #88aaff; }
  .sev-info { color: var(--dim); }
  .badge { padding: 0.15rem 0.5rem; border-radius: 2px; font-size: 0.75rem; font-weight: bold; }
  .badge-ok { background: #003322; color: var(--green); }
  .badge-warn { background: #332200; color: var(--yellow); }
  .badge-missing { background: #220000; color: var(--red); }
  .tech-tag { display: inline-block; background: #1a1a2e; color: var(--cyan); padding: 0.2rem 0.6rem; border: 1px solid var(--border); margin: 0.15rem; font-size: 0.8rem; }
  footer { margin-top: 3rem; color: var(--dim); font-size: 0.75rem; border-top: 1px solid var(--border); padding-top: 1rem; }
</style>
</head>
<body>
<div class="header">
  <h1>◆ KITFIND</h1>
  <div style="color:var(--dim); font-size:0.8rem; margin:0.25rem 0 1rem;">Security Reconnaissance Report</div>
  <div class="meta">
    <div class="meta-item"><label>TARGET</label><span>{{.Result.Target}}</span></div>
    <div class="meta-item"><label>DOMAIN</label><span>{{.Result.Domain}}</span></div>
    <div class="meta-item"><label>SCANNED AT</label><span>{{.Result.StartedAt.Format "2006-01-02 15:04:05"}}</span></div>
    <div class="meta-item"><label>DURATION</label><span>{{.Result.Duration}}</span></div>
    <div class="meta-item"><label>RISK SCORE</label><span class="risk-score {{gradeClass .Result.RiskGrade}}">{{.Result.RiskScore}}/100</span></div>
    <div class="meta-item"><label>RISK GRADE</label><span class="risk-score {{gradeClass .Result.RiskGrade}}">{{.Result.RiskGrade}}</span></div>
  </div>
</div>

{{if .Result.DNS}}
<h2>DNS Records</h2>
<table>
  <tr><th>TYPE</th><th>NAME</th><th>VALUE</th><th>TTL</th></tr>
  {{range .Result.DNS.Records}}
  <tr><td>{{.Type}}</td><td>{{.Name}}</td><td>{{.Value}}</td><td>{{.TTL}}</td></tr>
  {{end}}
</table>
{{if .Result.DNS.SPF}}<p><strong>SPF:</strong> {{.Result.DNS.SPF}}</p>{{end}}
{{if .Result.DNS.DMARC}}<p><strong>DMARC:</strong> {{.Result.DNS.DMARC}}</p>{{end}}
{{end}}

{{if .Result.SSL}}
<h2>SSL/TLS Certificate</h2>
<table>
  <tr><th>FIELD</th><th>VALUE</th></tr>
  <tr><td>TLS Version</td><td>{{.Result.SSL.TLSVersion}}</td></tr>
  <tr><td>Cipher Suite</td><td>{{.Result.SSL.CipherSuite}}</td></tr>
  <tr><td>Grade</td><td class="{{gradeClass .Result.SSL.Grade}}">{{.Result.SSL.Grade}}</td></tr>
  {{if .Result.SSL.Certificate}}
  <tr><td>Common Name</td><td>{{.Result.SSL.Certificate.Subject.CommonName}}</td></tr>
  <tr><td>Issuer</td><td>{{.Result.SSL.Certificate.Issuer.CommonName}}</td></tr>
  <tr><td>Expires</td><td>{{.Result.SSL.Certificate.NotAfter.Format "2006-01-02"}}</td></tr>
  <tr><td>Days Until Expiry</td><td>{{.Result.SSL.Certificate.DaysUntilExpiry}}</td></tr>
  <tr><td>Wildcard</td><td>{{.Result.SSL.Certificate.IsWildcard}}</td></tr>
  {{end}}
</table>
{{end}}

{{if .Result.HTTP}}
<h2>HTTP Security Headers</h2>
<table>
  <tr><th>HEADER</th><th>STATUS</th><th>SCORE</th><th>NOTES</th></tr>
  {{range .Result.HTTP.Checks}}
  <tr>
    <td>{{.Name}}</td>
    <td>
      {{if eq .Status "good"}}<span class="badge badge-ok">OK</span>
      {{else if eq .Status "warning"}}<span class="badge badge-warn">WARN</span>
      {{else if eq .Status "missing"}}<span class="badge badge-missing">MISSING</span>
      {{else}}<span class="badge">{{.Status}}</span>{{end}}
    </td>
    <td>{{.Score}}/100</td>
    <td>{{.Message}}</td>
  </tr>
  {{end}}
</table>
{{end}}

{{if .Result.Fingerprint}}
<h2>Technology Stack</h2>
<div>
  {{range .Result.Fingerprint.Technologies}}
  <span class="tech-tag">{{.Name}} <span style="color:var(--dim)">{{.Category}}</span></span>
  {{end}}
</div>
{{end}}

{{if .Result.Findings}}
<h2>Security Findings ({{len .Result.Findings}})</h2>
<table>
  <tr><th>#</th><th>SEVERITY</th><th>CATEGORY</th><th>TITLE</th><th>DESCRIPTION</th></tr>
  {{range $i, $f := .Result.Findings}}
  <tr>
    <td>{{inc $i}}</td>
    <td class="{{sevClass $f.Severity}}">{{upper $f.Severity}}</td>
    <td>{{$f.Category}}</td>
    <td>{{$f.Title}}</td>
    <td>{{$f.Description}}</td>
  </tr>
  {{end}}
</table>
{{end}}

<footer>Generated by KitFind v1.0.0 &mdash; {{.Generated}} &mdash; Authorized use only.</footer>
</body>
</html>`
